# http://docs.travis-ci.com/user/languages/go/
language: go

go:
  - 1.7
  - 1.7.x
  - 1.8
  - 1.8.x
  - 1.9
  - 1.9.x

os:
  - linux

install: true

script: script/cibuild

notifications:
  email: false
